#! /bin/csh -vxf

firefox &
sleep 25
set wid1=`xwininfo -root -tree | grep 'モバイル空間統計' | awk '{print $1}'`

./collector1 $wid1

firefox https://tokyo.mobakumap.jp/\#35.681236,139.767125,13z &
set wid2=`xwininfo -root -tree | grep 'モバイル空間統計' | awk '{print $1}'`

./collector2 $wid2

kill %1
