#! /bin/csh -vxf

#wget -q https://stopcovid19.metro.tokyo.lg.jp/index.html || exit 1

#firefox https://stopcovid19.metro.tokyo.lg.jp/index.html &

#sleep 20

set wid=`xwininfo -root -tree | grep '都内の最新感染動向' | grep Firefox | awk '{print $1}'`

xdotool key F3 || exit 1        # toggle from emacs to firefox
sleep 5  # wait for redraw

xdotool mousemove --window $wid 700 100 || exit 1
xdotool key --window $wid Home || exit 1
sleep 5
xwd -id $wid -silent -out tokyo.00

foreach cnt (01 02 03 04 05 06 07 08 09 10 11 12)
	xdotool key --window $wid Next || exit 1
	sleep 5
	xwd -id $wid -silent -out tokyo.$cnt
end




